/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated.premium'
import { Route as AuthenticatedModelerRouteImport } from './routes/_authenticated.modeler'
import { Route as AuthenticatedGuiaRouteImport } from './routes/_authenticated.guia'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAnalysesIdRouteImport } from './routes/_authenticated.analyses.$id'
import { Route as AuthenticatedProjectsIdAnalysesRouteImport } from './routes/_authenticated.projects.$id.analyses'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelerRoute = AuthenticatedModelerRouteImport.update({
  id: '/modeler',
  path: '/modeler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuiaRoute = AuthenticatedGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysesIdRoute = AuthenticatedAnalysesIdRouteImport.update({
  id: '/analyses/$id',
  path: '/analyses/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIdAnalysesRoute =
  AuthenticatedProjectsIdAnalysesRouteImport.update({
    id: '/projects/$id/analyses',
    path: '/projects/$id/analyses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guia': typeof AuthenticatedGuiaRoute
  '/modeler': typeof AuthenticatedModelerRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/projects/$id/analyses': typeof AuthenticatedProjectsIdAnalysesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guia': typeof AuthenticatedGuiaRoute
  '/modeler': typeof AuthenticatedModelerRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/projects/$id/analyses': typeof AuthenticatedProjectsIdAnalysesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guia': typeof AuthenticatedGuiaRoute
  '/_authenticated/modeler': typeof AuthenticatedModelerRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/analyses/$id': typeof AuthenticatedAnalysesIdRoute
  '/_authenticated/projects/$id/analyses': typeof AuthenticatedProjectsIdAnalysesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/guia'
    | '/modeler'
    | '/premium'
    | '/analyses/$id'
    | '/projects/$id/analyses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/guia'
    | '/modeler'
    | '/premium'
    | '/analyses/$id'
    | '/projects/$id/analyses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/guia'
    | '/_authenticated/modeler'
    | '/_authenticated/premium'
    | '/_authenticated/analyses/$id'
    | '/_authenticated/projects/$id/analyses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modeler': {
      id: '/_authenticated/modeler'
      path: '/modeler'
      fullPath: '/modeler'
      preLoaderRoute: typeof AuthenticatedModelerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guia': {
      id: '/_authenticated/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof AuthenticatedGuiaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyses/$id': {
      id: '/_authenticated/analyses/$id'
      path: '/analyses/$id'
      fullPath: '/analyses/$id'
      preLoaderRoute: typeof AuthenticatedAnalysesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/analyses': {
      id: '/_authenticated/projects/$id/analyses'
      path: '/projects/$id/analyses'
      fullPath: '/projects/$id/analyses'
      preLoaderRoute: typeof AuthenticatedProjectsIdAnalysesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuiaRoute: typeof AuthenticatedGuiaRoute
  AuthenticatedModelerRoute: typeof AuthenticatedModelerRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedAnalysesIdRoute: typeof AuthenticatedAnalysesIdRoute
  AuthenticatedProjectsIdAnalysesRoute: typeof AuthenticatedProjectsIdAnalysesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuiaRoute: AuthenticatedGuiaRoute,
  AuthenticatedModelerRoute: AuthenticatedModelerRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedAnalysesIdRoute: AuthenticatedAnalysesIdRoute,
  AuthenticatedProjectsIdAnalysesRoute: AuthenticatedProjectsIdAnalysesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AjudaRoute: AjudaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
